# golangci-linter configuration
# See https://github.com/golangci/golangci-lint#config-file for reference.

run:
  build-tags:
    - integration
  skip-dirs:
    - protogen/

linters-settings:
  funlen:
    lines: 80
    statements: 50
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - errors  # prefer golang.org/x/xerrors
      - log     # prefer github.com/sirupsen/logrus
      - github.com/gogo/protobuf  # don't use gogo, use github.com/golang/protobuf
      - github.com/pkg/errors     # prefer golang.org/x/xerrors
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 25
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0
  govet:
    # report about shadowed variables
    check-shadowing: false
  lll:
    line-length: 140
    tab-width: 4
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - interfacer

issues:
  exclude-rules:
    - text: "G204: Subprocess launched with function call as argument or cmd arguments"
      linters:
        - gosec
