version: '3'

services:
  brain:
    image: "luanguimaraesla/freegrow:development"
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
    - "start"
    - "brain"
    volumes:
    - .:/app
    ports:
      - 8000:8000
    depends_on:
    - postgres
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_DB: freegrow
      POSTGRES_USER: freegrow
      POSTGRES_PASSWORD: freegrow 
    ports:
    - 5432:5432
    volumes:
    - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}
