version: '3'

services:
  brain:
    image: "luanguimaraesla/freegrow:development"
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
    - "brain"
    volumes:
    - .:/app
    ports:
      - 8000:8000
    environment:
      FREEGROW_POSTGRES_HOST: postgres
      FREEGROW_POSTGRES_PORT: "5432"
      FREEGROW_POSTGRES_DATABASE: freegrow
      FREEGROW_POSTGRES_USERNAME: freegrow
      FREEGROW_POSTGRES_PASSWORD: freegrow
      FREEGROW_BIND_ADDRESS: 0.0.0.0:8000
      FREEGROW_REDIS_URL: "redis://redis:6379"
    depends_on:
    - postgres
    - redis
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_DB: freegrow
      POSTGRES_USER: freegrow
      POSTGRES_PASSWORD: freegrow
    ports:
    - 5432:5432
    volumes:
    - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6.0
    ports:
    - 6379:6379

volumes:
  db_data: {}
