FROM golang:1.15-alpine

ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux

WORKDIR /app

RUN apk update \
  && apk add make git

ADD . .

RUN make build && \
    make install

ENTRYPOINT ["freegrow"]
